orderServer: orderer.trias.com:7050

contractPath: /trias-contract/contract/

channelID: mychannel

ordererOrgName: Orderer

IPFSAddress: http://127.0.0.1:8080/ipfs/

dockerPath: github.com/hyperledger/fabric/singlepeer/chaincode/go/

port: 8088

ipfsAPIAddress: 127.0.0.1:5001

goPath: /opt/gopath/

conposeFilePath: src/github.com/hyperledger/fabric/singlepeer/docker-compose-cli.yaml

#don't change this
dataPath: /var/hyperledger/data/

packagePath: /trias-contract/backup/


couchdbInfo:
  port: 5984
  path: /var/hyperledger/data/couchdb0/_data/
  username: trias
  password: trias@Password